// <auto-generated />
namespace StocksDecision.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SD2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SD2));
        
        string IMigrationMetadata.Id
        {
            get { return "201710201030461_SD2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
